---
- name: Install WireGuard and related packages
  ansible.builtin.apt:
    name: "{{ __wireguard_packages }}"
    update_cache: true
    state: present

- name: Enable IPv4 forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true
    state: present
    reload: true

- name: Import server.yaml
  ansible.builtin.import_tasks: server.yaml

- name: Import peer.yaml
  ansible.builtin.import_tasks: peer.yaml
  when: wireguard_peers | length > 0
