---
name: Ansible-Galaxy CI

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: 'serhii9132.wireguard'

jobs:
  lint:
    name: Linting the syntax
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          path: 'serhii9132.wireguard'

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Install ansible-lint
        run: pip install ansible-lint

      - name: Run ansible-lint
        run: |
          ansible-lint --show-relpath .

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          path: 'serhii9132.wireguard'

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Install Ansible
        run: pip install ansible-core

      - name: Publish to Ansible Galaxy
        run: |
          ansible-galaxy role import \
          --token ${{ secrets.GALAXY_API_KEY }} \
          ${{ github.repository_owner }} \ \
          $(echo ${{ github.repository }} | cut -d '/' -f2)
